name: Emacs Lisp CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - "snapshot"
          - "30.1"
          - "29.4"
          - "28.2"
          # TODO: Re-add Emacs 27.2 once mcp.el is published on MELPA or ELPA

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Install dependencies
        run: |
          emacs -Q --batch \
                --eval "(require 'package)" \
                --eval "(add-to-list 'package-archives '(\"melpa-stable\" . \"https://stable.melpa.org/packages/\") t)" \
                --eval "(package-initialize)" \
                --eval "(package-refresh-contents)" \
                --eval "(package-install 'elisp-lint)" \
                --eval "(package-install 'package-lint)" \
                --eval "(require 'package-vc)" \
                --eval "(package-vc-install \"https://github.com/laurynas-biveinis/mcp.el/\")"

      - name: elisp-lint
        run: |
          emacs -Q --batch \
                --eval "(package-initialize)" \
                --eval "(require 'elisp-lint)" \
                -f elisp-lint-files-batch ./*.el

      - name: Run tests
        run: |
          emacs -Q --batch \
                --eval "(package-initialize)" \
                --eval "(require 'mcp)" \
                --eval "(add-to-list 'load-path (expand-file-name \".\"))" \
                --eval "(require 'ert)" \
                -l org-autotask-mcp.el -l org-autotask-mcp-test.el \
                -f ert-run-tests-batch-and-exit
